apiVersion: v1
kind: ConfigMap
metadata:
  name: upskill-config
data:
  FLASK_ENV: "production"
  SQLALCHEMY_TRACK_MODIFICATIONS: "False"
  RATELIMIT_STRATEGY: "fixed-window"
  SESSION_COOKIE_SECURE: "True"
  SESSION_COOKIE_HTTPONLY: "True"
  SESSION_COOKIE_SAMESITE: "Lax"
  WTF_CSRF_ENABLED: "True"
  BCRYPT_LOG_ROUNDS: "12"
